// 24_react/react-app/src/components/CreateUserComponent.js
import React, {useState} from 'react'
import {Link, useHistory} from 'react-router-dom';
import UserService from "../services/UserService";
import {useForm} from "react-hook-form";

const AddEmployeeComponent = () => {

    const [login, setLogin] = useState('');
    const [firstName, setFirstName] = useState('')
    const [lastName, setLastName] = useState('')
    const [email, setEmail] = useState('')
    const [password, setPassword] = useState('')
    const [passwordConfirm, setPasswordConfirm] = useState('')
    const [birthday, setBirthday] = useState('')
    const [role, setRole] = useState('')
    const history = useHistory();
    const {formState: {errors}, handleSubmit} = useForm();
    const [problems, setProblems] = useState(new Map());

    const saveUser = () => {

        const user = {
            login,
            firstName,
            lastName,
            email,
            password,
            passwordConfirm,
            birthday,
            role
        }
        console.log(user);

        UserService.createUser(user).then((response) => {
            if (response.status === 200) {
                history.push('/all')
            } else {
                console.log(response.data)
                setProblems(response.data)
            }
        }).catch(error => {
            console.log(error.response.data)
            setProblems(error.response.data)
        })
    }

    return (
        <div>
            <div className="container">
                <div className="row">
                    <div className="col-md-6 offset-md-3">
                        <h2 className={"text-center"}>Create User</h2>
                        <div className="card-body">
                            <form onSubmit={handleSubmit(saveUser)}>
                                <div className="form-group mb-2">
                                    <label className="form-label"> Login
                                        :</label>
                                    <input
                                        type="text"
                                        placeholder="Enter Login"
                                        name="login"
                                        className="form-control"
                                        value={login}
                                        onChange={(e) => setLogin(e.target.value)}
                                        required={true}>
                                    </input>
                                    {
                                        problems.loginError &&
                                        <div
                                            className="alert alert-warning">{problems.loginError}</div>
                                    }
                                    {
                                        problems.constraintLoginError &&
                                        <div
                                            className="alert alert-warning">{problems.constraintLoginError}</div>
                                    }
                                </div>

                                <div className="form-group mb-2">
                                    {
                                        problems.nameError &&
                                        <div
                                            className="alert alert-warning">{problems.nameError}</div>
                                    }
                                    <label className="form-label"> First Name
                                        :</label>
                                    <input
                                        type="text"
                                        placeholder="Enter First name"
                                        name="firstName"
                                        className="form-control"
                                        value={firstName}
                                        onChange={(e) => setFirstName(e.target.value)}
                                        required={true}>
                                    </input>
                                </div>

                                <div className="form-group mb-2">
                                    <label className="form-label"> Last Name
                                        :</label>
                                    <input
                                        type="text"
                                        placeholder="Enter last name"
                                        name="lastName"
                                        className="form-control"
                                        value={lastName}
                                        onChange={(e) => setLastName(e.target.value)}
                                        required={true}>
                                    </input>
                                </div>

                                <div className="form-group mb-2">
                                    <label className="form-label"> Email
                                        :</label>
                                    <input
                                        type="email"
                                        placeholder="Enter email "
                                        name="email"
                                        className="form-control"
                                        value={email}
                                        onChange={(e) => setEmail(e.target.value)}
                                        required={true}>
                                    </input>
                                    {
                                        problems.emailError &&
                                        <div
                                            className="alert alert-warning">{problems.emailError}</div>
                                    }
                                </div>

                                <div className="form-group mb-2">
                                    <label className="form-label"> Password
                                        :</label>
                                    <input
                                        type="password"
                                        placeholder="Enter password "
                                        name="password"
                                        className="form-control"
                                        value={password}
                                        onChange={(e) => setPassword(e.target.value)}
                                        required={true}>
                                    </input>
                                </div>

                                <div className="form-group mb-2">
                                    <label className="form-label"> Confirm
                                        Password
                                        :</label>
                                    <input
                                        type="password"
                                        placeholder="Confirm Password "
                                        name="passwordConfirm"
                                        className="form-control"
                                        value={passwordConfirm}
                                        onChange={(e) => setPasswordConfirm(e.target.value)}
                                        required={true}>
                                    </input>
                                    {
                                        problems.passwordError &&
                                        <div
                                            className="alert alert-warning">{problems.passwordError}</div>
                                    }
                                </div>

                                <div className="form-group mb-2">
                                    <label className="form-label">
                                        Birthday
                                        :</label>
                                    <input
                                        type="date"
                                        placeholder="Enter Birthday "
                                        name="passwordConfirm"
                                        className="form-control"
                                        value={birthday}
                                        onChange={(e) => setBirthday(e.target.value)}
                                        required={true}>
                                    </input>
                                    {
                                        problems.dateError &&
                                        <div
                                            className="alert alert-warning">{problems.dateError}</div>
                                    }
                                </div>

                                <div className="form-group mb-2">
                                    <label className="form-label">
                                        Role :</label>
                                    <select value={role}
                                            onChange={(e) => setRole(e.target.value)}
                                            className="form-control"
                                            required={true}>
                                        <option value=""/>
                                        <option value="USER">USER</option>
                                        <option value="ADMIN">ADMIN</option>
                                    </select>
                                </div>

                                <div>
                                    <button type={"submit"}
                                            className="btn btn-success"> Create
                                    </button>
                                    <Link to="/all"
                                          className="btn btn-outline-danger">Cancel</Link>
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>)
}

export default AddEmployeeComponent

// 23_angular/angular-app/src/app/create-user/create-user.component.ts
import {Component, OnInit} from '@angular/core';
import {UserForCreate} from "../user-models/user-for-create";
import {UserService} from "../service/user.service";
import {Router} from "@angular/router";

@Component({
  selector: 'app-create-user',
  templateUrl: './create-user.component.html',
  styleUrls: ['./create-user.component.css']
})
export class CreateUserComponent implements OnInit {

  user: UserForCreate = new UserForCreate();
  problems: Map<string, string> = new Map<string, string>();

  constructor(private userService: UserService,
              private router: Router) {
  }

  ngOnInit(): void {
  }

  saveUser() {
    this.userService.createUser(this.user).subscribe({
      next: (data) => {
        console.log(data);
        this.goToUsersList();
      },
      error: error => {
        this.problems.clear();
        for (const [key, value] of Object.entries(error.error)) {
          this.problems.set(key, <string>value);
        }
        console.log(error.error);
      }
    })
  }

  goToUsersList() {
    this.router.navigate(['/users/all']);
  }

  onSubmit() {
    console.log(this.user);
    this.saveUser();
  }
}

<div class="col-md-6 offset-md-3">
  <h1 class="text-center"> Create User </h1>
  <form ngNativeValidate (ngSubmit)="onSubmit()" action="#">

    <div class="form-group">
      <label> Login </label>
      <input type="text" class="form-control" id="login" name = "login"
             [(ngModel)]="user.login" name="login" required #login="ngModel">
    </div>

    <div *ngIf="problems.has('loginError')" class="alert alert-warning">
      {{ problems.get('loginError') }}
    </div>
    <div *ngIf="problems.has('constraintLoginError')" class="alert alert-warning">
      {{ problems.get('constraintLoginError') }}
    </div>

    <div class="form-group">
      <label> First Name</label>
      <input type="text" class="form-control" id="firstName"
             [(ngModel)]="user.firstName" name="firstName" required>
    </div>

    <div *ngIf="problems.has('nameError')" class="alert alert-warning">
      {{ problems.get('nameError') }}
    </div>

    <div class="form-group">
      <label> Last Name</label>
      <input type="text" class="form-control" id="lastName"
             [(ngModel)]="user.lastName" name="lastName" required>
    </div>

    <div class="form-group">
      <label> Password</label>
      <input type="password" class="form-control" id="password"
             [(ngModel)]="user.password" name="password" required>
    </div>

    <div class="form-group">
      <label> Confirm Password </label>
      <input type="password" class="form-control" id="passwordConfirm"
             [(ngModel)]="user.passwordConfirm" name="passwordConfirm" required>
    </div>

    <div *ngIf="problems.has('passwordError')" class="alert alert-warning">
      {{ problems.get('passwordError') }}
    </div>

    <div class="form-group">
      <label> Email </label>
      <input type="email" class="form-control" id="email"
             [(ngModel)]="user.email" name="email" required>
    </div>

    <div *ngIf="problems.has('emailError')" class="alert alert-warning">
      {{ problems.get('emailError') }}
    </div>

    <div class="form-group">
      <label> Birthday</label>
      <input type="date" class="form-control" id="birthday"
             [(ngModel)]="user.birthday" name="birthday" required >
    </div>

    <div *ngIf="problems.has('dateError')" class="alert alert-warning">
      {{ problems.get('dateError') }}
    </div>

    <label> Role</label>
    <select [(ngModel)]="user.role" name="role" class="form-control" required>
      <option value="USER">USER</option>
      <option value="ADMIN">ADMIN</option>
    </select>

    <div>
      <button type="submit" class="btn btn-success"
              style="margin: 0 auto; margin-top: 10px; width: 49.8%"> Create
      </button>
      <a href="/users/all" class="btn btn-outline-danger" style="width: 49%;
                    margin-top: 10px; margin-left: 5px">Cancel</a>
    </div>

  </form>
</div>
